### ISSUE TITLE
demo link in README.md

### ISSUE THREAD

**Issue by PicoJr** [kdex/earthbound-battle-backgrounds#2]
Hello,

It looks like the demo url in `README.md` has not been updated

* url in the readme: <https://kdex.github.io/earthbound-battle-backgrounds>
* good url from the project description: <https://github.kdex.de/earthbound-battle-backgrounds/>

> You can find a full-screen demo [here](https://kdex.github.io/earthbound-battle-backgrounds)

Cool project btw =)

Best regards,

PicoJr.

**Comment by kdex** [comment]
Yeah, I know. This repository is a bunch of commits behind my local branch, where this has already been fixed last year. I'll push my changes ASAP.

Thanks for reporting!
