### ISSUE TITLE
How to generate backgrounds-truncated.dat

### ISSUE THREAD

**Issue by xianzhe18** [kdex/earthbound-battle-backgrounds#5]
Thanks for this nice repo.
I am replicating this for the sake to change background with my png files.
But I am stuck with backgrounds-truncated.dat file. I don't know the structure, and how it was generated.
Please make a note or documentary to help me.

Thanks in advance

**Comment by kdex** [comment]
You should be able to generate `backgrounds-truncated.dat` by dumping Earthbound with an offset of `0x0A0200` and a length of 121056 bytes.

Anyway, you should be able to clone this project and modify it to your needs; no need to redo the math.

**Comment by xianzhe18** [comment]
Thanks for your quick reply.
I am asking if I can generate the data with my own PNG files.
If so, please indicate me a proper documentation.

**Comment by kdex** [comment]
Oh, sorry, I might have misunderstood you.

`backgrounds-truncated.dat` does not *only* contain the bitmaps, it's a tiny dump directly from Earthbound. It also contains motion parameters and a bunch of other stuff. Just to be clear: I didn't create those bitmaps, I'm just reading them from the game.

They aren't as dynamic as you might think, as well: They have fixed sizes and are compressed with HAL's proprietary format. [My (de)compressor](https://github.com/kdex/hell) might help with (de)compressing the data.

Rendering data should be stored in `[0x0ADEA1, 0x0AF457]`. For more information about how the data is stored, see [BackgroundGraphics](https://github.com/kdex/earthbound-battle-backgrounds/blob/master/src/rom/BackgroundGraphics.js). Note that the pointer math is currently offset by some number. I'll probably revert this soon.

Hope this helps.

**Comment by xianzhe18** [comment]
Can we talk about it on skype? Mine is miron.steel@outlook.com

**Comment by kdex** [comment]
> Can I import image files with your (de)compressor?

In theory, yes, you should be able to. Don't expect it to work with a high-level format such as `png`, though.

> There are some block handling functions in BackgroundGraphics and RomGraphics, but it's hard to understand without knowledge in the structure.

The game's ROM data is compressed. This compression format is subdivided into blocks. You can check out my [documentation](https://github.com/kdex/hell) of how this format works. Blocks are just an abstraction over byte ranges within the ROM and offer a means to be decompressed, that's it.

`arrayROMGraphics` is needed for drawing tiles during rendering, see [here](https://github.com/kdex/earthbound-battle-backgrounds/blob/32df24aec8ca851d408cb15720164a4dd4b8b164/src/rom/ROMGraphics.js#L28-L49).

**Comment by xianzhe18** [comment]
Thanks for your help, my app has a progress to change background image with my PNG file.
I got some questions yet.
1. It is not necessary to change `arrayROMGraphics` according to background image, is it?
2. How can I change the number of tiles?
